version: '2'

services:
  appserver:
    build: .
    ports:
      - 9292:9292
    volumes:
      - ./:/app/
  webpack_asset_builder:
    build:
      context: .
      dockerfile: Dockerfile.webpack-asset-builder
    volumes:
      - ./:/app/
